### PR TITLE
Fix pattern detection in relative path condition (#89)

### PR DESCRIPTION
**Pull request by ludovic-pourrat**
Error in IDE "Failed to check if current file is included" #89

### CODE REVIEW

**Comment by markbrockhoff** [comment]
Hi, thanks for your contribution.

Your code looks good but could you please add a test case for the problem it fixes? Maybe just reuse the failing parameters reported inside the issue. There's already a data driven test for the `isFileIncluded` function.

In order to release it, please also add a "Fixes" entry to the file CHANGELOG.md under the [Unreleased] section.
This project uses [KeepAChangelog](https://keepachangelog.com) for automatic versioning. In order to trigger a release you also need to bump the pluginVersion inside the gradle.properties from 3.0.0 to 3.0.1.

**Comment by tintin92350** [comment]
> Hi, thanks for your contribution.
> 
> Your code looks good but could you please add a test case for the problem it fixes? Maybe just reuse the failing parameters reported inside the issue. There's already a data driven test for the `isFileIncluded` function.
> 
> In order to release it, please also add a "Fixes" entry to the file CHANGELOG.md under the [Unreleased] section. This project uses [KeepAChangelog](https://keepachangelog.com) for automatic versioning. In order to trigger a release you also need to bump the pluginVersion inside the gradle.properties from 3.0.0 to 3.0.1.

Hi ! Well this code fix the existing unit tests that fails because of pattern like `**/*.yaml` that can be set by users. So I think that we don't have to create another tests as they already exists ? 😊

**Comment by markbrockhoff** [comment]
> > Hi, thanks for your contribution.
> > Your code looks good but could you please add a test case for the problem it fixes? Maybe just reuse the failing parameters reported inside the issue. There's already a data driven test for the `isFileIncluded` function.
> > In order to release it, please also add a "Fixes" entry to the file CHANGELOG.md under the [Unreleased] section. This project uses [KeepAChangelog](https://keepachangelog.com) for automatic versioning. In order to trigger a release you also need to bump the pluginVersion inside the gradle.properties from 3.0.0 to 3.0.1.
> 
> Hi ! Well this code fix the existing unit tests that fails because of pattern like `**/*.yaml` that can be set by users. So I think that we don't have to create another tests as they already exists ? 😊

I see, could it be that you're working on windows?
Because on mac and linux (our CI) all tests were already passing beforehand.

**Comment by tintin92350** [comment]
> > > Hi, thanks for your contribution.
> > > Your code looks good but could you please add a test case for the problem it fixes? Maybe just reuse the failing parameters reported inside the issue. There's already a data driven test for the `isFileIncluded` function.
> > > In order to release it, please also add a "Fixes" entry to the file CHANGELOG.md under the [Unreleased] section. This project uses [KeepAChangelog](https://keepachangelog.com) for automatic versioning. In order to trigger a release you also need to bump the pluginVersion inside the gradle.properties from 3.0.0 to 3.0.1.
> > 
> > 
> > Hi ! Well this code fix the existing unit tests that fails because of pattern like `**/*.yaml` that can be set by users. So I think that we don't have to create another tests as they already exists ? 😊
> 
> I see, could it be that you're working on windows? Because on mac and linux (our CI) all tests were already passing beforehand.

Yes ! We are working on windows environment. Mmh maybe do you want us to add an os detection condition to make the code works a little bit differently on windows ?

**Comment by markbrockhoff** [comment]
> > > > Hi, thanks for your contribution.
> > > > Your code looks good but could you please add a test case for the problem it fixes? Maybe just reuse the failing parameters reported inside the issue. There's already a data driven test for the `isFileIncluded` function.
> > > > In order to release it, please also add a "Fixes" entry to the file CHANGELOG.md under the [Unreleased] section. This project uses [KeepAChangelog](https://keepachangelog.com) for automatic versioning. In order to trigger a release you also need to bump the pluginVersion inside the gradle.properties from 3.0.0 to 3.0.1.
> > > 
> > > 
> > > Hi ! Well this code fix the existing unit tests that fails because of pattern like `**/*.yaml` that can be set by users. So I think that we don't have to create another tests as they already exists ? 😊
> > 
> > 
> > I see, could it be that you're working on windows? Because on mac and linux (our CI) all tests were already passing beforehand.
> 
> Yes ! We are working on windows environment. Mmh maybe do you want us to add an os detection condition to make the code works a little bit differently on windows ?

No, it think we can make it work with the same logic for windows and unix, maintaining two sets of logic is just more effort and might introduce bugs. I'd like to avoid that if possible.
I just created the branch `run-ci-on-windows` inside this repo. Could you please rebase your branch on that so we can properly verify that all tests are passing on windows as well as on unix systems?

**Comment by ludovic-pourrat** [comment]
This might be ok now for this PR, let us know.

Thanks !

**Comment by markbrockhoff** [comment]
Hi @ludovic-pourrat, this looks good. Thanks again for your contribution :)
I'll merge and release this, please keep in mind that it can take up to a few days until the new release was reviewed and approved by Jetbrains and is visible in the marketplace.

**Pull request merged**
